spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hospital_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}


# Note: H2 settings removed to run exclusively on MySQL
# JPA/Hibernate configs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server config
server.port=8080

# Error Handling Fix
server.error.include-message=always
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
